#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Structured Streaming 结构化流演示

本脚本演示 Spark Structured Streaming 的基本概念、操作和使用方法。
"""

import os
import sys

print("Structured Streaming 结构化流演示")
print("=" * 50)

# 1. Structured Streaming 基本概念
def structured_streaming_basics():
    print("\n1. Structured Streaming 基本概念:")
    print("- Structured Streaming 是 Spark 2.0 引入的流处理 API")
    print("- 基于 DataFrame API，提供了声明式的流处理能力")
    print("- 将流数据视为无限增长的表")
    print("- 支持与批处理相同的操作")
    print("- 提供了 exactly-once 语义保证")

# 2. 流处理模型
def streaming_model():
    print("\n2. 流处理模型:")
    print("- 输入表: 从数据源接收的流数据")
    print("- 查询: 对输入表的转换操作")
    print("- 结果表: 查询结果")
    print("- 输出: 将结果表输出到外部系统")
    print("- 处理模式:")
    print("  - Append 模式: 只输出新添加的行")
    print("  - Complete 模式: 输出所有结果")
    print("  - Update 模式: 只输出更新的行")

# 3. 数据源连接
def data_source_connection():
    print("\n3. 数据源连接:")
    print("- 从 TCP 套接字读取:")
    print("  from pyspark.sql import SparkSession")
    print("  spark = SparkSession.builder.appName('StructuredStreamingDemo').getOrCreate()")
    print("  lines = spark.readStream.format('socket').option('host', 'localhost').option('port', 9999).load()")
    print("- 从 Kafka 读取:")
    print("  df = spark.readStream.format('kafka')")
    print("      .option('kafka.bootstrap.servers', 'localhost:9092')")
    print("      .option('subscribe', 'test-topic')")
    print("      .load()")
    print("- 从文件系统读取:")
    print("  from pyspark.sql.types import StructType, StructField, StringType, IntegerType")
    print("  schema = StructType([")
    print("      StructField('name', StringType(), True),")
    print("      StructField('age', IntegerType(), True),")
    print("      StructField('salary', IntegerType(), True)")
    print("  ])")
    print("  df = spark.readStream.format('csv')")
    print("      .option('header', 'true')")
    print("      .schema(schema)")
    print("      .load('hdfs://path/to/directory')")

# 4. 流数据处理
def streaming_data_processing():
    print("\n4. 流数据处理:")
    print("- 基本操作:")
    print("  from pyspark.sql import SparkSession")
    print("  from pyspark.sql.functions import split, explode")
    print("  spark = SparkSession.builder.appName('StructuredStreamingDemo').getOrCreate()")
    print("  # 从 TCP 套接字读取数据")
    print("  lines = spark.readStream.format('socket').option('host', 'localhost').option('port', 9999).load()")
    print("  # 分词")
    print("  words = lines.select(explode(split(lines['value'], ' ')).alias('word'))")
    print("  # 计数")
    print("  wordCounts = words.groupBy('word').count()")
    print("- 窗口操作:")
    print("  from pyspark.sql.functions import window, current_timestamp")
    print("  # 添加时间戳")
    print("  linesWithTimestamp = lines.withColumn('timestamp', current_timestamp())")
    print("  # 分词并保留时间戳")
    print("  wordsWithTimestamp = linesWithTimestamp.select(")
    print("      explode(split(linesWithTimestamp['value'], ' ')).alias('word'),")
    print("      linesWithTimestamp['timestamp']")
    print("  )")
    print("  # 窗口计数")
    print("  windowedCounts = wordsWithTimestamp.groupBy(")
    print("      window(wordsWithTimestamp['timestamp'], '10 minutes', '5 minutes'),")
    print("      wordsWithTimestamp['word']")
    print("  ).count()")

# 5. 输出操作
def output_operations():
    print("\n5. 输出操作:")
    print("- 输出到控制台:")
    print("  from pyspark.sql import SparkSession")
    print("  from pyspark.sql.functions import split, explode")
    print("  spark = SparkSession.builder.appName('StructuredStreamingDemo').getOrCreate()")
    print("  lines = spark.readStream.format('socket').option('host', 'localhost').option('port', 9999).load()")
    print("  words = lines.select(explode(split(lines['value'], ' ')).alias('word'))")
    print("  wordCounts = words.groupBy('word').count()")
    print("  query = wordCounts.writeStream")
    print("      .outputMode('complete')")
    print("      .format('console')")
    print("      .start()")
    print("- 输出到文件系统:")
    print("  query = wordCounts.writeStream")
    print("      .outputMode('append')")
    print("      .format('parquet')")
    print("      .option('path', 'hdfs://path/to/output')")
    print("      .option('checkpointLocation', 'hdfs://path/to/checkpoint')")
    print("      .start()")
    print("- 输出到 Kafka:")
    print("  query = wordCounts.writeStream")
    print("      .outputMode('update')")
    print("      .format('kafka')")
    print("      .option('kafka.bootstrap.servers', 'localhost:9092')")
    print("      .option('topic', 'output-topic')")
    print("      .option('checkpointLocation', 'hdfs://path/to/checkpoint')")
    print("      .start()")

# 6. 检查点
def checkpointing():
    print("\n6. 检查点:")
    print("- 检查点的作用:")
    print("  - 保存流处理的状态")
    print("  - 支持故障恢复")
    print("  - 确保 exactly-once 语义")
    print("- 设置检查点:")
    print("  from pyspark.sql import SparkSession")
    print("  from pyspark.sql.functions import split, explode")
    print("  spark = SparkSession.builder.appName('StructuredStreamingDemo').getOrCreate()")
    print("  lines = spark.readStream.format('socket').option('host', 'localhost').option('port', 9999).load()")
    print("  words = lines.select(explode(split(lines['value'], ' ')).alias('word'))")
    print("  wordCounts = words.groupBy('word').count()")
    print("  query = wordCounts.writeStream")
    print("      .option('checkpointLocation', 'hdfs://path/to/checkpoint')")
    print("      .start()")

# 7. 流处理控制
def streaming_control():
    print("\n7. 流处理控制:")
    print("- 启动查询:")
    print("  from pyspark.sql import SparkSession")
    print("  from pyspark.sql.functions import split, explode")
    print("  spark = SparkSession.builder.appName('StructuredStreamingDemo').getOrCreate()")
    print("  lines = spark.readStream.format('socket').option('host', 'localhost').option('port', 9999).load()")
    print("  words = lines.select(explode(split(lines['value'], ' ')).alias('word'))")
    print("  wordCounts = words.groupBy('word').count()")
    print("  query = wordCounts.writeStream.start()")
    print("- 等待查询完成:")
    print("  query.awaitTermination()")
    print("- 停止查询:")
    print("  query.stop()")
    print("- 查看查询状态:")
    print("  print(query.status)")
    print("  print(query.lastProgress)")

# 8. 状态管理
def state_management():
    print("\n8. 状态管理:")
    print("- 有状态操作:")
    print("  # 定义更新函数")
    print("  def updateFunction(newValues, runningCount):")
    print("      if runningCount is None:")
    print("          runningCount = 0")
    print("      return sum(newValues) + runningCount if newValues else runningCount")
    print("  # 使用 mapGroupsWithState")
    print("  from pyspark.sql.functions import mapGroupsWithState")
    print("  # 实现状态更新")
    print("  # 注意: mapGroupsWithState 在 Python API 中有限制")

# 9. 示例应用
def example_applications():
    print("\n9. 示例应用:")
    print("- 实时单词计数:")
    print("  from pyspark.sql import SparkSession")
    print("  from pyspark.sql.functions import split, explode")
    print("  ")
    print("  spark = SparkSession.builder.appName('WordCount').getOrCreate()")
    print("  ")
    print("  # 从 TCP 套接字读取数据")
    print("  lines = spark.readStream.format('socket').option('host', 'localhost').option('port', 9999).load()")
    print("  ")
    print("  # 分词")
    print("  words = lines.select(explode(split(lines['value'], ' ')).alias('word'))")
    print("  ")
    print("  # 计数")
    print("  wordCounts = words.groupBy('word').count()")
    print("  ")
    print("  # 输出到控制台")
    print("  query = wordCounts.writeStream")
    print("      .outputMode('complete')")
    print("      .format('console')")
    print("      .start()")
    print("  ")
    print("  query.awaitTermination()")
    print("- 窗口单词计数:")
    print("  from pyspark.sql import SparkSession")
    print("  from pyspark.sql.functions import split, explode, window, current_timestamp")
    print("  ")
    print("  spark = SparkSession.builder.appName('WindowedWordCount').getOrCreate()")
    print("  ")
    print("  # 从 TCP 套接字读取数据")
    print("  lines = spark.readStream.format('socket').option('host', 'localhost').option('port', 9999).load()")
    print("  ")
    print("  # 添加时间戳")
    print("  linesWithTimestamp = lines.withColumn('timestamp', current_timestamp())")
    print("  ")
    print("  # 分词")
    print("  words = linesWithTimestamp.select(")
    print("      explode(split(linesWithTimestamp['value'], ' ')).alias('word'),")
    print("      linesWithTimestamp['timestamp']")
    print("  )")
    print("  ")
    print("  # 窗口计数")
    print("  windowedCounts = words.groupBy(")
    print("      window(words['timestamp'], '10 minutes', '5 minutes'),")
    print("      words['word']")
    print("  ).count()")
    print("  ")
    print("  # 输出到控制台")
    print("  query = windowedCounts.writeStream")
    print("      .outputMode('complete')")
    print("      .format('console')")
    print("      .start()")
    print("  ")
    print("  query.awaitTermination()")

# 10. 最佳实践
def best_practices():
    print("\n10. 最佳实践:")
    print("- 数据模式:")
    print("  - 始终为流数据指定明确的 schema")
    print("  - 使用 StructType 定义 schema")
    print("- 性能优化:")
    print("  - 合理设置批处理间隔")
    print("  - 使用适当的输出模式")
    print("  - 优化查询计划")
    print("- 容错:")
    print("  - 启用检查点")
    print("  - 选择可靠的数据源")
    print("  - 处理重复数据")
    print("- 监控:")
    print("  - 监控流处理延迟")
    print("  - 监控处理速率")
    print("  - 监控状态大小")
    print("- 部署:")
    print("  - 在生产环境中使用集群模式")
    print("  - 合理配置资源")

if __name__ == "__main__":
    # 执行所有演示
    structured_streaming_basics()
    streaming_model()
    data_source_connection()
    streaming_data_processing()
    output_operations()
    checkpointing()
    streaming_control()
    state_management()
    example_applications()
    best_practices()
    
    print("\n" + "=" * 50)
    print("演示完成！")